// 中英双语字典 + t() 取词。服务端和客户端共用（纯函数，无 hook）
export type Lang = "zh" | "en";

type Dict = Record<string, string>;

const zh: Dict = {
  // 通用
  brand: "DateDrop",
  back_home: "回首页",
  loading: "请稍等…",
  // 登录
  "login.tagline": "周四收到计划，\n周六只管出门。",
  "login.blurb": "两个人各自滑一遍约会卡片，剩下的交给我们——场地、天气、时间线，每周四自动送达，你们只保留否决权。",
  "login.welcome_back": "欢迎回来",
  "login.start": "开始你们的第一周",
  "login.sub_signin": "登录后继续你们的约会计划",
  "login.sub_signup": "注册只要十秒，之后把链接发给另一半",
  "login.your_name": "你的名字",
  "login.name_ph": "对方会看到这个名字",
  "login.email": "邮箱",
  "login.password": "密码",
  "login.password_ph": "至少 6 位",
  "login.signin": "登录",
  "login.create": "创建账号",
  "login.to_signup": "还没有账号？注册一个",
  "login.to_signin": "已有账号？直接登录",
  // 绑定
  "pair.title": "先把你们俩连起来",
  "pair.sub": "一个人创建空间，另一个人通过链接或邀请码加入",
  "pair.creating": "创建中…",
  "pair.create": "创建我们的空间",
  "pair.have_code": "收到了对方的邀请码？",
  "pair.code_ph": "8 位邀请码",
  "pair.join": "加入",
  "pair.code_bad": "邀请码无效或已被使用",
  "invite.bad_title": "这个邀请链接不可用",
  "invite.bad_body": "可能已被使用、已失效，或者这是你自己创建的邀请。",
  // 首页
  "home.this_week": "本周计划",
  "home.us": "你们",
  "home.discover": "发现",
  "home.match_pool": "匹配池",
  "home.sign_out": "退出登录",
  "home.swipe_title": "滑卡盲选",
  "home.swipe_sub": "对方看不到你的选择",
  "home.pool_count": "匹配池里有 {n} 个你们都想去的约会",
  "home.wait_partner": "等另一半加入",
  "home.invite_hint": "链接发给 TA，点开即绑定",
  "home.no_match": "还没有匹配。两个人都滑过同一张卡并且都选了想去，它就会出现在这里。",
  "home.copy": "复制",
  "home.copied": "已复制",
  // 滑卡
  "swipe.home": "首页",
  "swipe.like": "想去",
  "swipe.nope": "算了",
  "swipe.round_done": "这一轮刷完了",
  "swipe.empty": "没有新卡片了",
  "swipe.summary": "你右滑了 {n} 张。等 TA 也刷完，匹配会出现在首页的匹配池里。",
  "swipe.matched": "你们都想去",
  // 计划卡
  "plan.delivered": "本周已送达",
  "plan.none_title": "本周还没有计划",
  "plan.none_body": "目标周六：{date}。基于你们的匹配池和当天天气，生成一条可以直接执行的时间线。",
  "plan.mood": "这周心情",
  "plan.skippable": "可跳过",
  "plan.mood_chill": "想躺平",
  "plan.mood_spark": "来点刺激",
  "plan.mood_fete": "有事庆祝",
  "plan.generate": "生成本周计划",
  "plan.saturday": "周六",
  "plan.precip": "降水",
  "plan.station": "第 {n} 站",
  "plan.swap": "换",
  "plan.locked": "定了",
  "plan.swap_title": "换这一站 · {time}",
  "plan.swap_sub": "横滑挑一个，其他站不动",
  "plan.current": "当前",
  "plan.selected": "选中",
  "plan.free": "免费",
  "plan.use_this": "就用这个",
  "plan.swap_to_this": "换成这个",
  "plan.sent_title": "已发给 {name}",
  "plan.sent_body": "{name} 点头后，这周六就锁定了",
  "plan.both_title": "周六见，就这么定了",
  "plan.both_body": "出发前一晚我们会再提醒你们一次",
  "plan.status_both": "两个人都确认了 · 周六见",
  "plan.status_mine": "你已确认 · 等 {name} 确认",
  "plan.status_partner": "{name} 已确认 · 就等你点头",
  "plan.status_none": "你俩都还没点头",
  "plan.undo": "撤回",
  "plan.waiting": "等 {name} 点头",
  "plan.commit": "就这个了",
  "plan.reroll": "整体换",
  "plan.add_calendar": "加进两个人的日历",
  "plan.generating": "正在查天气、翻你们的匹配池、挑场地……大约需要半分钟",
  "plan.gen_fail": "生成失败",
  "plan.note_locked": "已锁定你的选择。若任何一方换站，需要重新确认。",
  "plan.empty_card": "另一半加入后，这里每周四会出现你们的周六计划",
  // 场地类别
  "kind.hike": "徒步", "kind.park": "公园", "kind.beach": "海滩", "kind.garden": "花园",
  "kind.viewpoint": "观景", "kind.activity": "活动", "kind.water": "水上", "kind.museum": "博物馆",
  "kind.art-walk": "艺术", "kind.cinema": "电影", "kind.landmark": "地标", "kind.food": "吃饭",
  "kind.dessert": "甜点", "kind.winery": "酒庄", "kind.quirky": "好玩", "kind.amusement": "游乐",
  "kind.aquarium": "水族", "kind.district": "街区", "kind.roadtrip": "公路", "kind.nightlife": "夜生活",
  "kind.event": "活动", "kind.market": "市集", "kind.coffee": "咖啡", "kind.brewery": "精酿",
  "kind.default": "玩",
  // 周四推送邮件
  "email.subject": "你们这周六的约会计划到了",
  "email.preheader": "打开看看，满意就一键确认，哪站不喜欢可以单独换。",
  "email.hello": "DateDrop · 周四掉落",
  "email.intro": "这周六给你俩排好了。满意就一键确认，哪一站不喜欢可以单独换掉，其他站不动。",
  "email.cta": "查看并确认",
  "email.footer": "出发前一晚我们会再提醒你们一次。",
};

const en: Dict = {
  brand: "DateDrop",
  back_home: "Back home",
  loading: "One sec…",
  "login.tagline": "Plans land Thursday,\nyou just show up Saturday.",
  "login.blurb": "You each swipe through date ideas once. We handle the rest — venues, weather, a timeline — delivered every Thursday. You keep veto power.",
  "login.welcome_back": "Welcome back",
  "login.start": "Start your first week",
  "login.sub_signin": "Sign in to pick up your date plans",
  "login.sub_signup": "Takes ten seconds — then send the link to your other half",
  "login.your_name": "Your name",
  "login.name_ph": "Your partner will see this",
  "login.email": "Email",
  "login.password": "Password",
  "login.password_ph": "At least 6 characters",
  "login.signin": "Sign in",
  "login.create": "Create account",
  "login.to_signup": "No account yet? Sign up",
  "login.to_signin": "Already have an account? Sign in",
  "pair.title": "First, connect the two of you",
  "pair.sub": "One of you creates the space, the other joins with a link or invite code",
  "pair.creating": "Creating…",
  "pair.create": "Create our space",
  "pair.have_code": "Got an invite code from your partner?",
  "pair.code_ph": "8-char code",
  "pair.join": "Join",
  "pair.code_bad": "That invite code is invalid or already used",
  "invite.bad_title": "This invite link isn't usable",
  "invite.bad_body": "It may have been used, expired, or it's an invite you created yourself.",
  "home.this_week": "This week",
  "home.us": "The two of you",
  "home.discover": "Discover",
  "home.match_pool": "Matches",
  "home.sign_out": "Sign out",
  "home.swipe_title": "Blind swipe",
  "home.swipe_sub": "Your partner can't see your picks",
  "home.pool_count": "{n} date ideas you both want to do",
  "home.wait_partner": "Waiting for your other half",
  "home.invite_hint": "Send the link — one tap and you're paired",
  "home.no_match": "No matches yet. When you both swipe right on the same card, it shows up here.",
  "home.copy": "Copy",
  "home.copied": "Copied",
  "swipe.home": "Home",
  "swipe.like": "Want to",
  "swipe.nope": "Pass",
  "swipe.round_done": "That's the round",
  "swipe.empty": "No new cards",
  "swipe.summary": "You swiped right on {n}. Once your partner finishes too, matches show up in your pool.",
  "swipe.matched": "You both want to",
  "plan.delivered": "Delivered this week",
  "plan.none_title": "No plan yet this week",
  "plan.none_body": "Target Saturday: {date}. Built from your match pool and the day's weather into a timeline you can just follow.",
  "plan.mood": "This week's mood",
  "plan.skippable": "skippable",
  "plan.mood_chill": "Low-key",
  "plan.mood_spark": "Something fun",
  "plan.mood_fete": "Celebrating",
  "plan.generate": "Generate this week's plan",
  "plan.saturday": "Sat",
  "plan.precip": "rain",
  "plan.station": "Stop {n}",
  "plan.swap": "Swap",
  "plan.locked": "Set",
  "plan.swap_title": "Swap this stop · {time}",
  "plan.swap_sub": "Swipe to pick one — other stops stay put",
  "plan.current": "current",
  "plan.selected": "Picked",
  "plan.free": "Free",
  "plan.use_this": "Keep this",
  "plan.swap_to_this": "Swap to this",
  "plan.sent_title": "Sent to {name}",
  "plan.sent_body": "Once {name} says yes, Saturday is locked in",
  "plan.both_title": "It's set — see you Saturday",
  "plan.both_body": "We'll remind you both the night before",
  "plan.status_both": "Both confirmed · see you Saturday",
  "plan.status_mine": "You're in · waiting on {name}",
  "plan.status_partner": "{name} is in · just waiting on you",
  "plan.status_none": "Neither of you has said yes yet",
  "plan.undo": "Undo",
  "plan.waiting": "Waiting on {name}",
  "plan.commit": "I'm in",
  "plan.reroll": "New plan",
  "plan.add_calendar": "Add to both calendars",
  "plan.generating": "Checking weather, your match pool, picking venues… about half a minute",
  "plan.gen_fail": "Generation failed",
  "plan.note_locked": "Your pick is locked. If either of you swaps a stop, you'll both re-confirm.",
  "plan.empty_card": "Once your partner joins, your Saturday plan shows up here every Thursday",
  "kind.hike": "Hike", "kind.park": "Park", "kind.beach": "Beach", "kind.garden": "Garden",
  "kind.viewpoint": "View", "kind.activity": "Activity", "kind.water": "On water", "kind.museum": "Museum",
  "kind.art-walk": "Art", "kind.cinema": "Cinema", "kind.landmark": "Landmark", "kind.food": "Eat",
  "kind.dessert": "Dessert", "kind.winery": "Winery", "kind.quirky": "Quirky", "kind.amusement": "Rides",
  "kind.aquarium": "Aquarium", "kind.district": "District", "kind.roadtrip": "Road trip", "kind.nightlife": "Nightlife",
  "kind.event": "Event", "kind.market": "Market", "kind.coffee": "Coffee", "kind.brewery": "Brewery",
  "kind.default": "Go",
  "email.subject": "Your Saturday date plan is here",
  "email.preheader": "Take a look — confirm in one tap, or swap any stop you don't love.",
  "email.hello": "DateDrop · Thursday drop",
  "email.intro": "We lined up this Saturday for the two of you. Confirm in one tap, or swap any single stop you don't love — the rest stays put.",
  "email.cta": "View & confirm",
  "email.footer": "We'll remind you both the night before.",
};

const dicts: Record<Lang, Dict> = { zh, en };

export function t(lang: Lang, key: string, params?: Record<string, string | number>): string {
  const s = dicts[lang]?.[key] ?? zh[key] ?? key;
  if (!params) return s;
  return s.replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ""));
}

/** 动态内容按语言取（en 缺失时回落 zh） */
export function pick(lang: Lang, zhVal: string, enVal?: string | null): string {
  return lang === "en" && enVal ? enVal : zhVal;
}

export function kindLabel(lang: Lang, category: string): string {
  const key = `kind.${category}`;
  const has = dicts[lang]?.[key] ?? zh[key];
  return has ? t(lang, key) : t(lang, "kind.default");
}
