-- DateDrop 种子数据：40 张约会卡片 + 60 个湾区场地
-- 场地营业时间均未校验（hours_verified=false），上线前跑一次批量校验

-- ============ 约会卡片（盲选池） ============
insert into public.date_cards (title, description, emoji, style_tags, budget_level, duration_hours, seasons) values
('日落徒步', '挑一条看海的步道，赶在日落前登顶', '🌅', '{outdoor,active,romantic}', 1, 2.5, '{spring,summer,fall,winter}'),
('海边野餐', '带上毯子、面包和起司，找一片海滩躺到天黑', '🧺', '{outdoor,chill,romantic}', 1, 3, '{spring,summer,fall}'),
('攀岩馆初体验', '室内抱石，互相打气，摔在垫子上笑半天', '🧗', '{active,playful}', 2, 2.5, '{spring,summer,fall,winter}'),
('陶艺手作课', '一人捏一个歪歪扭扭的杯子，交换着用', '🏺', '{creative,chill}', 2, 2, '{spring,summer,fall,winter}'),
('农夫市集早午餐', '周六早市逛吃逛吃，买花买水果', '🥐', '{food,city,chill}', 2, 3, '{spring,summer,fall,winter}'),
('博物馆一日', '挑个特展慢慢看，博物馆咖啡馆坐一下午', '🖼️', '{culture,chill}', 2, 4, '{spring,summer,fall,winter}'),
('酒庄半日游', '开车去酒乡，品酒看葡萄园日落', '🍷', '{food,romantic,roadtrip}', 3, 6, '{spring,summer,fall}'),
('桌游咖啡馆', '点两杯拿铁，杀一下午桌游', '🎲', '{playful,chill}', 1, 3, '{spring,summer,fall,winter}'),
('密室逃脱', '60 分钟限时逃脱，考验默契', '🗝️', '{playful,adventure}', 2, 1.5, '{spring,summer,fall,winter}'),
('KTV 之夜', '包个小包间唱到嗓子哑', '🎤', '{playful,nightlife}', 2, 3, '{spring,summer,fall,winter}'),
('观星夜', '开去光污染少的山头，裹着毯子认星座', '✨', '{outdoor,romantic,adventure}', 1, 3, '{spring,summer,fall}'),
('城市骑行', '租两辆单车沿海边或公园骑一圈', '🚲', '{active,city,outdoor}', 1, 2.5, '{spring,summer,fall}'),
('皮划艇 / SUP', '水上约会，翻船也是回忆', '🛶', '{active,water,adventure}', 2, 2, '{spring,summer,fall}'),
('温泉 SPA 放松日', '什么都不干，就泡着', '♨️', '{chill,romantic}', 3, 4, '{spring,summer,fall,winter}'),
('现场音乐演出', '小 livehouse 或大场馆，跟着低音点头', '🎸', '{nightlife,culture}', 3, 3, '{spring,summer,fall,winter}'),
('棒球赛之夜', '热狗、啤酒、第七局伸懒腰', '⚾', '{playful,city}', 2, 4, '{spring,summer,fall}'),
('二手书店巡游', '互相给对方挑一本书，配咖啡', '📚', '{chill,culture,city}', 1, 2.5, '{spring,summer,fall,winter}'),
('摄影散步', '一人一台相机，互拍街拍', '📷', '{creative,city,outdoor}', 1, 2.5, '{spring,summer,fall,winter}'),
('在家做饭挑战赛', '限定食材或主题，各做一道菜互评', '🍳', '{food,home,playful}', 1, 3, '{spring,summer,fall,winter}'),
('烘焙课', '学做可颂或马卡龙，带成品回家', '🥖', '{creative,food}', 2, 3, '{spring,summer,fall,winter}'),
('植物园漫步', '温室花园慢慢逛，认识奇怪植物', '🌿', '{outdoor,chill}', 1, 2, '{spring,summer,fall,winter}'),
('水族馆约会', '看水母发呆一小时', '🪼', '{culture,chill}', 2, 3, '{spring,summer,fall,winter}'),
('美食车夜市', '一摊一样，吃成米其林评委', '🌮', '{food,city,nightlife}', 2, 2.5, '{spring,summer,fall}'),
('爵士酒吧之夜', '昏暗灯光、现场爵士、两杯调酒', '🎷', '{nightlife,romantic}', 3, 3, '{spring,summer,fall,winter}'),
('脱口秀之夜', '看 open mic 或专场，笑一晚上', '🎙️', '{nightlife,playful}', 2, 2.5, '{spring,summer,fall,winter}'),
('迷你高尔夫', '室内创意球道，输的请奶茶', '⛳', '{playful}', 2, 2, '{spring,summer,fall,winter}'),
('保龄球之夜', '复古球馆，配薯条和汽水', '🎳', '{playful}', 2, 2, '{spring,summer,fall,winter}'),
('溜冰约会', '牵手滑冰，摔了也有人扶', '⛸️', '{active,playful}', 2, 2, '{fall,winter}'),
('海岸线自驾', '沿一号公路开，灯塔、海豹、悬崖', '🚗', '{roadtrip,outdoor,romantic}', 1, 5, '{spring,summer,fall,winter}'),
('果园采摘', '草莓、苹果或南瓜，按季节来', '🍓', '{outdoor,food}', 2, 3, '{summer,fall}'),
('一夜露营', '篝火、棉花糖、帐篷里聊到睡着', '⛺', '{outdoor,adventure}', 2, 18, '{spring,summer,fall}'),
('双人舞蹈课', 'Salsa 或 Swing 入门，踩脚也算亲密接触', '💃', '{active,creative}', 2, 1.5, '{spring,summer,fall,winter}'),
('Sip & Paint', '边喝小酒边画画，作品丑得很登对', '🎨', '{creative,romantic}', 2, 2.5, '{spring,summer,fall,winter}'),
('城市寻宝', '给对方设计一条解谜路线，终点有惊喜', '🧭', '{playful,city,adventure}', 1, 3, '{spring,summer,fall,winter}'),
('在家电影院', '投影仪、毯子、爆米花，三连看', '🍿', '{home,chill}', 1, 4, '{spring,summer,fall,winter}'),
('日出突袭行动', '凌晨出发看日出，回来吃顿大早餐', '🌄', '{outdoor,adventure,romantic}', 1, 4, '{spring,summer,fall,winter}'),
('渡轮过湾一日', '坐船过湾，对岸小镇吃吃逛逛', '⛴️', '{city,water,chill}', 2, 5, '{spring,summer,fall}'),
('城市夜景打卡', '找全城最佳视野，看夜景', '🌃', '{outdoor,city,romantic}', 1, 2, '{spring,summer,fall,winter}'),
('动物园半日', '看动物摸鱼，给彼此起动物外号', '🦒', '{playful,outdoor}', 2, 3.5, '{spring,summer,fall,winter}'),
('街头艺术散步', '壁画街区走一圈，找出最喜欢的一面墙', '🖌️', '{culture,city,creative}', 1, 2, '{spring,summer,fall,winter}');

-- ============ 湾区场地库 ============
insert into public.venues (name, area, category, tags, price_level, duration_hours, indoor, notes) values
-- 旧金山
('Lands End Trail', 'San Francisco', 'hike', '{ocean,views,easy}', 1, 2, false, '海崖步道，看金门大桥侧面和 Sutro Baths 遗迹，日落极佳'),
('Golden Gate Park', 'San Francisco', 'park', '{picnic,gardens,bike}', 1, 3, false, '超大城市公园，野餐、划船、逛馆一站式'),
('Japanese Tea Garden', 'San Francisco', 'garden', '{chill,photo,tea}', 2, 1.5, false, 'GG Park 内日式庭园，有茶屋'),
('SF Botanical Garden', 'San Francisco', 'garden', '{plants,chill}', 1, 2, false, '就在 GG Park，可与茶园串联'),
('California Academy of Sciences', 'San Francisco', 'museum', '{aquarium,planetarium,rainforest}', 3, 4, true, '自然博物馆+水族馆+天文馆三合一；周四晚有 21+ NightLife 之夜'),
('de Young Museum', 'San Francisco', 'museum', '{art,tower-view}', 2, 3, true, '顶楼观景塔免费'),
('SFMOMA', 'San Francisco', 'museum', '{modern-art}', 2, 3, true, '现代艺术，馆内咖啡好坐'),
('Exploratorium', 'San Francisco', 'museum', '{interactive,science}', 3, 3, true, '周四晚 After Dark 是 18+ 场，约会神选'),
('Ferry Building Marketplace', 'San Francisco', 'food', '{farmers-market,brunch}', 2, 2, true, '周六早农夫市集最热闹，配湾景'),
('Mission Dolores Park', 'San Francisco', 'park', '{picnic,views,people-watching}', 1, 2, false, '晴天野餐圣地，旁边就是 Bi-Rite 冰淇淋'),
('Clarion Alley 壁画巷', 'San Francisco', 'art-walk', '{murals,street-art}', 1, 1, false, 'Mission 区壁画，配墨西哥卷饼一条龙'),
('Twin Peaks', 'San Francisco', 'viewpoint', '{night-view,sunset}', 1, 1, false, '全城夜景，风大记得带外套'),
('Palace of Fine Arts', 'San Francisco', 'landmark', '{photo,romantic}', 1, 1, false, '罗马式圆顶+天鹅湖，拍照圣地'),
('Crissy Field', 'San Francisco', 'beach', '{picnic,bridge-view,walk}', 1, 2, false, '看金门大桥最经典的草坪海滩'),
('Baker Beach', 'San Francisco', 'beach', '{sunset,bridge-view}', 1, 2, false, '金门大桥+落日同框'),
('Musée Mécanique', 'San Francisco', 'quirky', '{arcade,vintage,free}', 1, 1, true, '渔人码头古董街机博物馆，免费进场投币玩'),
('Ghirardelli Square', 'San Francisco', 'dessert', '{chocolate,sundae}', 2, 1, true, '经典巧克力圣代'),
('Urban Putt', 'San Francisco', 'activity', '{mini-golf,bar}', 2, 2, true, '室内创意迷你高尔夫+餐吧'),
('Bi-Rite Creamery', 'San Francisco', 'dessert', '{ice-cream}', 1, 0.5, true, '配 Dolores Park 食用最佳'),
('Tartine Bakery', 'San Francisco', 'food', '{bakery,brunch}', 2, 1, true, '要排队但值得'),
('Oracle Park', 'San Francisco', 'event', '{baseball,giants}', 3, 4, false, '能看海湾的棒球场，赛季查赛程'),
('Japantown', 'San Francisco', 'district', '{mochi,karaoke,shopping}', 2, 3, true, '纪伊国屋书店+和菓子+KTV 一条龙'),
('Presidio Tunnel Tops', 'San Francisco', 'park', '{picnic,views}', 1, 2, false, '新建公园，桥景野餐'),
('Aquarium of the Bay', 'San Francisco', 'aquarium', '{tunnel}', 2, 2, true, 'Pier 39 旁，海底隧道'),
('Pandora Karaoke & Bar', 'San Francisco', 'nightlife', '{ktv,private-room}', 2, 3, true, 'SOMA 私人包间 KTV'),
('Presidio Bowl', 'San Francisco', 'activity', '{bowling}', 2, 2, true, 'Presidio 园区里的保龄球馆'),
('Off the Grid Fort Mason', 'San Francisco', 'food', '{food-trucks,night-market}', 2, 2.5, false, '季节性美食车夜市，去前查当季日程'),
-- 东湾
('Lake Merritt', 'Oakland', 'park', '{lake-walk,gondola,picnic}', 1, 2, false, '绕湖 5km，可坐贡多拉船'),
('Tilden Regional Park', 'Berkeley', 'park', '{steam-train,carousel,farm,hike}', 1, 3, false, '蒸汽小火车+旋转木马+小农场，童心约会'),
('Berkeley Marina', 'Berkeley', 'park', '{kite,sunset,walk}', 1, 2, false, '放风筝看日落'),
('Redwood Regional Park', 'Oakland', 'hike', '{redwoods,shade}', 1, 3, false, '东湾红杉林，比 Muir Woods 人少'),
('Berkeley Rose Garden', 'Berkeley', 'garden', '{roses,views}', 1, 1, false, '春夏玫瑰盛开，能看金门'),
('Oakland Museum of California', 'Oakland', 'museum', '{art,history}', 2, 3, true, '加州历史与艺术'),
('Fentons Creamery', 'Oakland', 'dessert', '{ice-cream,classic}', 2, 1, true, '百年老店冰淇淋'),
('Grand Lake Theatre', 'Oakland', 'cinema', '{historic,movie}', 2, 3, true, '复古影院'),
('Mount Diablo Summit', 'Walnut Creek', 'roadtrip', '{summit,views}', 1, 4, false, '晴天据说能看到内华达山脉'),
-- 半岛 / 南湾
('Stanford Dish Loop', 'Palo Alto', 'hike', '{easy,sunset,paved}', 1, 2, false, '铺装环线，日落散步首选'),
('Cantor Arts Center + 斯坦福校园', 'Palo Alto', 'museum', '{rodin,free,campus-walk}', 1, 3, true, '免费，罗丹雕塑园+校园散步'),
('Filoli Historic House & Garden', 'Woodside', 'garden', '{estate,flowers}', 3, 3, false, '庄园花园，春季绝美，节假日要预订'),
('Computer History Museum', 'Mountain View', 'museum', '{nerdy,tech}', 2, 3, true, '程序员约会保留节目'),
('Shoreline Lake', 'Mountain View', 'water', '{paddle-boat,kayak}', 2, 2, false, '踩船/皮划艇租赁，新手友好'),
('Apple Park Visitor Center', 'Cupertino', 'quirky', '{tech,rooftop}', 1, 1, true, '屋顶看飞碟总部'),
('Santana Row', 'San Jose', 'district', '{dinner,shopping,walk}', 3, 3, false, '晚餐+散步的安全牌'),
('Winchester Mystery House', 'San Jose', 'quirky', '{tour,spooky}', 3, 2, true, '怪宅导览，万圣节季更带感'),
('Japanese Friendship Garden', 'San Jose', 'garden', '{koi,chill}', 1, 1.5, false, 'Kelley Park 内，喂锦鲤'),
('Mission Peak', 'Fremont', 'hike', '{sunrise,strenuous}', 1, 4, false, '日出突袭首选，强度偏高，量力'),
('San Pedro Square Market', 'San Jose', 'food', '{food-hall,night}', 2, 2, true, '室内美食广场，晚上有气氛'),
('Don Edwards Wildlife Refuge', 'Fremont', 'park', '{birds,walk,quiet}', 1, 2, false, '湿地观鸟，安静系约会'),
-- 海岸 / 北湾 / 自驾
('Half Moon Bay State Beach', 'Half Moon Bay', 'beach', '{picnic,sunset}', 1, 3, false, '秋天周边有南瓜田'),
('Devil''s Slide Trail', 'Pacifica', 'hike', '{paved,ocean,easy}', 1, 1.5, false, '悬崖海景铺装步道，轻松'),
('Pacifica Pier', 'Pacifica', 'beach', '{pier,sunset}', 1, 1.5, false, '海上日落；旁边有"全美最美 Taco Bell"，玩梗约会'),
('Muir Woods', 'Mill Valley', 'hike', '{redwoods,iconic}', 2, 3, false, '红杉国家纪念地，停车必须提前预约！'),
('Sausalito', 'Sausalito', 'district', '{ferry,seaside,lunch}', 2, 4, false, '从 SF 坐渡轮往返，经典一日游'),
('Point Reyes Lighthouse', 'Point Reyes', 'roadtrip', '{lighthouse,elephant-seals}', 1, 6, false, '车程远但值，冬季能看象海豹'),
('Mount Tamalpais', 'Mill Valley', 'hike', '{above-fog,sunset}', 1, 4, false, '云海之上看日落'),
('Domaine Carneros', 'Napa', 'winery', '{sparkling,terrace}', 3, 2, false, '起泡酒庄园露台品酒，建议预约'),
('Año Nuevo State Park', 'Pescadero', 'roadtrip', '{elephant-seals,guided}', 2, 4, false, '12-3 月象海豹季需预订导览'),
('Santa Cruz Beach Boardwalk', 'Santa Cruz', 'amusement', '{rides,arcade,beach}', 2, 5, false, '夏季海滨游乐园'),
('Monterey Bay Aquarium', 'Monterey', 'aquarium', '{world-class,otters}', 3, 5, true, '车程约 2h，适合全天自驾日'),
('Movement Climbing Gym', 'Sunnyvale / SF 多店', 'activity', '{climbing,day-pass}', 2, 2.5, true, '抱石初体验买 day pass，租鞋即可');
